### PR TITLE
added stats column

### PR DESCRIPTION
**Pull request by maddhruv**

### CODE REVIEW

**Comment by Man-Jain** [comment]
I think if we can show just the numbers that would be more interesting. iIf thats possible.

**Comment by maddhruv** [comment]
> I think if we can show just the numbers that would be more interesting
we need to update the stats everytime

otherwise, the idea for putting the links is fine - anyone can check the stats even if they aren't updated in the repo

and if hacktoberfest if already keeping the records, why should we!

**Comment by Man-Jain** [comment]
Okay It also good. Cause putting the data dynmically is really tricky.

**Comment by akashlakhera** [comment]
Until we can figure out how to put the data dynamically into markdown let's go with it.

**Pull request merged**
