### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sokratis12GR**
Not sure if I did this right here

### CODE REVIEW

**Comment by maddhruv** [comment]
resolve the conflicts and do the necessary

**Comment by sokratis12GR** [comment]
Wait what?
What exactly do you mean ?
(The space, accidentally I added 2 spaces instead of one and then removed the space)

**Comment by maddhruv** [comment]
Okay! seems to be fine!
I actually checked your last commit!

Welcome :tada:

**Comment by sokratis12GR** [comment]
Thank you ^.^

**Pull request merged**
